project: shopper_conversion_propensity

xgboost:
  objective: binary:logistic
  param_grid:
    max_depth: [3, 5, 7]
    learning_rate: [0.1, 0.3, 0.5]
    n_estimators: [100, 300, 500]

bigquery:
  project_id: shopper_conversion_propensity
  service_account_file: /path/to/service_account.json
